if exists('g:vscode')
    " VSCode extension
else
    " ordinary vim

    set relativenumber
set number
set nocompatible

syntax on
set background=dark

    " highlight matching parens, braces, brackets, etc
    set showmatch

    set hidden

    set autoindent
    set smartindent
    set shiftwidth=4

    if !has('nvim')
colorscheme jamesnzl

        " make scrolling and painting fast
        " ttyfast kept for vim compatibility but not needed for nvim
        set ttyfast lazyredraw

	nnoremap <A-j> :m .+1<CR>==
	nnoremap <A-k> :m .-2<CR>==
	inoremap <A-j> <Esc>:m .+1<CR>==gi
	inoremap <A-k> <Esc>:m .-2<CR>==gi
	vnoremap <A-j> :m '>+1<CR>gv=gv
	vnoremap <A-k> :m '<-2<CR>gv=gv

	let c='a'
	while c <= 'z'
	  exec "set <A-".c.">=\e".c
	  exec "imap \e".c." <A-".c.">"
	  let c = nr2char(1+char2nr(c))
	endw

	set ttimeout ttimeoutlen=50
    endif

endif
